package dev.carlsen.protondrive.sdk.nodes

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** Ports CreateFileDto - POST drive/v2/volumes/{volumeID}/files. */
@Serializable
data class CreateFileRequest(
    @SerialName("ParentLinkID") val parentLinkId: String,
    @SerialName("Name") val name: String,
    @SerialName("Hash") val hash: String,
    @SerialName("MIMEType") val mimeType: String,
    @SerialName("NodeKey") val nodeKey: String,
    @SerialName("NodePassphrase") val nodePassphrase: String,
    @SerialName("NodePassphraseSignature") val nodePassphraseSignature: String,
    @SerialName("ContentKeyPacket") val contentKeyPacket: String,
    @SerialName("ContentKeyPacketSignature") val contentKeyPacketSignature: String? = null,
    /** Confusingly named "Address" (not "Email") here, unlike most other Drive endpoints. */
    @SerialName("SignatureAddress") val signatureAddress: String,
    @SerialName("ClientUID") val clientUid: String? = null,
    @SerialName("IntendedUploadSize") val intendedUploadSize: Long? = null,
)

@Serializable
data class CreateFileResponse(@SerialName("Code") val code: Int, @SerialName("File") val file: CreatedFileDto)

@Serializable
data class CreatedFileDto(@SerialName("ID") val id: String, @SerialName("RevisionID") val revisionId: String)

/** Ports VerificationData - GET drive/v2/volumes/{volumeID}/links/{linkID}/revisions/{revisionID}/verification. */
@Serializable
data class VerificationDataResponse(
    @SerialName("Code") val code: Int,
    /** Base64-encoded random bytes - XORed with each block's leading encrypted bytes to prove the client actually holds the content session key. */
    @SerialName("VerificationCode") val verificationCode: String,
)

/** Ports RequestUploadInput - POST drive/blocks. */
@Serializable
data class RequestUploadRequest(
    @SerialName("LinkID") val linkId: String,
    @SerialName("RevisionID") val revisionId: String,
    @SerialName("AddressID") val addressId: String,
    @SerialName("VolumeID") val volumeId: String,
    @SerialName("BlockList") val blockList: List<RequestUploadBlock>,
    @SerialName("ThumbnailList") val thumbnailList: List<RequestUploadThumbnail> = emptyList(),
)

@Serializable
data class RequestUploadBlock(
    /** Must be consecutive starting at 1. */
    @SerialName("Index") val index: Int,
    @SerialName("Verifier") val verifier: VerifierDto,
)

/** 1 = Preview (512px, max 69632 bytes encrypted), 2 = HDPreview (1920px, max 1052672 bytes encrypted), 3 = MachineLearning. Only Preview is ever generated by this SDK/CLI. */
@Serializable
data class RequestUploadThumbnail(@SerialName("Type") val type: Int)

@Serializable
data class VerifierDto(@SerialName("Token") val token: String)

/** Ports RequestUploadResponse. */
@Serializable
data class RequestUploadResponse(
    @SerialName("Code") val code: Int,
    @SerialName("UploadLinks") val uploadLinks: List<UploadLinkDto> = emptyList(),
    @SerialName("ThumbnailLinks") val thumbnailLinks: List<ThumbnailLinkDto> = emptyList(),
)

@Serializable
data class UploadLinkDto(
    @SerialName("Index") val index: Int,
    @SerialName("BareURL") val bareUrl: String,
    @SerialName("Token") val token: String,
)

/** Note the field is named ThumbnailType here, not Type as on the request side. */
@Serializable
data class ThumbnailLinkDto(
    @SerialName("ThumbnailType") val thumbnailType: Int,
    @SerialName("BareURL") val bareUrl: String,
    @SerialName("Token") val token: String,
)

/** Ports CommitRevisionDto - PUT drive/v2/volumes/{volumeID}/files/{linkID}/revisions/{revisionID}. */
@Serializable
data class CommitRevisionRequest(
    @SerialName("ManifestSignature") val manifestSignature: String,
    @SerialName("SignatureAddress") val signatureAddress: String,
    @SerialName("XAttr") val xAttr: String? = null,
    @SerialName("ChecksumVerified") val checksumVerified: Boolean = false,
    @SerialName("Photo") val photo: String? = null,
)

@Serializable
data class CommitRevisionResponse(@SerialName("Code") val code: Int)
